# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/157rqm1PFPEddp4bzZ-lrF8JeyNtCZCEu
"""

"""
Self-Pruning Neural Network
Tredence Analytics — AI Engineering Internship Assignment

Deliverables:
    Part 1 — PrunableLinear custom layer
    Part 2 — Sparsity regularization loss (normalized L1)
    Part 3 — Training, evaluation, lambda comparison

Key design decisions:
    - gate_scores init to zeros → sigmoid(0)=0.5, midpoint start
    - Kaiming uniform weight init (correct for ReLU networks)
    - Normalized sparsity loss: always in [0,1], lambda values interpretable
    - Sparsity threshold=0.01 (assignment spec)
    - CosineAnnealingLR for stable convergence
    - Gradient clipping for stability
    - 4-layer architecture with BatchNorm for better accuracy
"""

# ── Imports ──────────────────────────────────────────────────
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
import random

# ── Reproducibility ──────────────────────────────────────────
def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


# ── Device ───────────────────────────────────────────────────
set_seed(42)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")


# ── Part 1: PrunableLinear ────────────────────────────────────
class PrunableLinear(nn.Module):
    """
    Custom linear layer with learnable gates.

    Each weight w_ij has a corresponding gate g_ij = sigmoid(s_ij).

    Forward pass:
        gates          = sigmoid(gate_scores)       → [0, 1]
        pruned_weights = weight * gates             → element-wise masking
        output         = F.linear(x, pruned_weights, bias)

    When g_ij → 0, the weight is effectively pruned (dead connection).
    Gradients flow through both weight and gate_scores via autograd:
        ∂loss/∂weight      = ∂loss/∂pruned_w · sigmoid(gate_scores)
        ∂loss/∂gate_scores = ∂loss/∂pruned_w · weight · sigmoid'(gate_scores)

    Init choices:
        weight      → Kaiming uniform (designed for ReLU activations)
        gate_scores → zeros (sigmoid(0)=0.5, gates start at midpoint)
    """

    def __init__(self, in_features, out_features):
        super().__init__()
        self.in_features  = in_features
        self.out_features = out_features

        self.weight = nn.Parameter(torch.empty(out_features, in_features))
        nn.init.kaiming_uniform_(self.weight, nonlinearity='relu')

        self.bias = nn.Parameter(torch.zeros(out_features))

        # gate_scores: same shape as weight, registered as parameter
        # zeros init → sigmoid(0)=0.5, gates start fully open at midpoint
        self.gate_scores = nn.Parameter(
            torch.zeros(out_features, in_features)
        )

    def forward(self, x):
        # sigmoid: differentiable, bounded [0,1], gradient flows to gate_scores
        gates          = torch.sigmoid(self.gate_scores)
        pruned_weights = self.weight * gates
        return F.linear(x, pruned_weights, self.bias)

    def get_gates(self):
        """Returns gate values detached — for metrics only, no gradient cost."""
        with torch.no_grad():
            return torch.sigmoid(self.gate_scores)

    def extra_repr(self):
        return f'in={self.in_features}, out={self.out_features}'


# ── Model ─────────────────────────────────────────────────────
class PrunableMLP(nn.Module):
    """
    Feedforward network using only PrunableLinear layers.

    Architecture: 3072 → 1024 → 512 → 256 → 10
    BatchNorm applied before ReLU (pre-activation style).
    No Dropout — gate sparsity acts as the sole regulariser.

    Input: flattened CIFAR-10 image (32×32×3 = 3072)
    """

    def __init__(self):
        super().__init__()

        self.fc1 = PrunableLinear(3072, 1024)
        self.bn1 = nn.BatchNorm1d(1024)

        self.fc2 = PrunableLinear(1024, 512)
        self.bn2 = nn.BatchNorm1d(512)

        self.fc3 = PrunableLinear(512, 256)
        self.bn3 = nn.BatchNorm1d(256)

        # Output layer — no BN, raw logits into cross-entropy
        self.fc4 = PrunableLinear(256, 10)

    def forward(self, x):
        x = x.view(x.size(0), -1)          # flatten → (B, 3072)
        x = F.relu(self.bn1(self.fc1(x)))
        x = F.relu(self.bn2(self.fc2(x)))
        x = F.relu(self.bn3(self.fc3(x)))
        return self.fc4(x)


# ── Part 2: Sparsity Loss ─────────────────────────────────────
def sparsity_loss(model):
    """
    Normalized L1 norm of all gate values across PrunableLinear layers.

    Why L1 encourages sparsity:
        - Gradient of |g| = sign(g) → constant push toward zero
        - Unlike L2 (gradient ∝ magnitude), L1 pushes ALL gates equally
        - This drives values to exact zero, not just near-zero
        - Normalization keeps result in [0,1] → lambda values interpretable

    Formula: sum(sigmoid(gate_scores)) / total_gate_count
    """
    total = torch.tensor(0.0, device=next(model.parameters()).device)
    count = 0
    for m in model.modules():
        if isinstance(m, PrunableLinear):
            # Must recompute sigmoid here (not get_gates) to keep gradient path
            gates  = torch.sigmoid(m.gate_scores)
            total  = total + gates.sum()
            count += gates.numel()
    return total / count


# ── Sparsity Metrics ──────────────────────────────────────────
def compute_sparsity(model, threshold=0.01):
    """
    Total sparsity: % of gates below threshold.
    threshold=0.01 per assignment spec.
    Gate < 0.01 → weight contributes <1% of magnitude → effectively pruned.
    """
    total = pruned = 0
    for m in model.modules():
        if isinstance(m, PrunableLinear):
            g       = m.get_gates()
            total  += g.numel()
            pruned += (g < threshold).sum().item()
    return 100 * pruned / total


def layerwise_sparsity(model, threshold=0.01):
    """Per-layer sparsity breakdown."""
    out = []
    for m in model.modules():
        if isinstance(m, PrunableLinear):
            g = m.get_gates()
            out.append(100 * (g < threshold).sum().item() / g.numel())
    return out


# ── Data ──────────────────────────────────────────────────────
def get_loaders(batch_size=128):
    """
    CIFAR-10 with correct per-channel normalization stats.
    Training: RandomHorizontalFlip for light augmentation.
    """
    normalize = transforms.Normalize(
        mean=(0.4914, 0.4822, 0.4465),
        std =(0.2470, 0.2435, 0.2616)
    )

    train_transform = transforms.Compose([
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        normalize,
    ])

    test_transform = transforms.Compose([
        transforms.ToTensor(),
        normalize,
    ])

    train = torchvision.datasets.CIFAR10(
        root="./data", train=True,  download=True, transform=train_transform)
    test  = torchvision.datasets.CIFAR10(
        root="./data", train=False, download=True, transform=test_transform)

    return (
        torch.utils.data.DataLoader(
            train, batch_size=batch_size, shuffle=True,
            num_workers=2, pin_memory=True),
        torch.utils.data.DataLoader(
            test,  batch_size=batch_size, shuffle=False,
            num_workers=2, pin_memory=True)
    )


# ── Part 3: Training ──────────────────────────────────────────
def train(model, loader, lam, epochs=25):
    """
    Training loop.
    Total Loss = CrossEntropyLoss + λ * sparsity_loss(model)

    - Adam optimizer, lr=0.001
    - CosineAnnealingLR: smoothly decays lr to 1e-5 by final epoch
    - Gradient clipping max_norm=1.0 for stability
    - Fixed lambda throughout (no warmup scheduling)
    """
    model.to(device)
    optimizer = optim.Adam(model.parameters(), lr=0.001)
    scheduler = optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=epochs, eta_min=1e-5
    )
    criterion = nn.CrossEntropyLoss()

    for epoch in range(1, epochs + 1):
        model.train()
        total_ce = 0.0
        total_sp = 0.0

        for images, labels in loader:
            images, labels = images.to(device), labels.to(device)
            optimizer.zero_grad()

            out     = model(images)
            ce      = criterion(out, labels)
            sp      = sparsity_loss(model)
            loss    = ce + lam * sp

            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()

            total_ce += ce.item()
            total_sp += sp.item()

        scheduler.step()

        if epoch % 5 == 0 or epoch == 1:
            sparsity = compute_sparsity(model)
            print(f"  Epoch {epoch:3d}/{epochs}  "
                  f"CE={total_ce/len(loader):.4f}  "
                  f"SpLoss={total_sp/len(loader):.4f}  "
                  f"sparsity={sparsity:.1f}%  "
                  f"lr={scheduler.get_last_lr()[0]:.2e}")


# ── Evaluation ────────────────────────────────────────────────
def evaluate(model, loader):
    model.eval()
    correct = total = 0
    with torch.no_grad():
        for images, labels in loader:
            images, labels = images.to(device), labels.to(device)
            preds   = model(images).argmax(dim=1)
            correct += (preds == labels).sum().item()
            total   += labels.size(0)
    return 100 * correct / total


# ── Visualization ─────────────────────────────────────────────
def plot_gates(model, lam, threshold=0.01):
    """
    Gate value distribution histogram.

    Successful pruning shows:
        - Large spike near 0  (pruned gates — L1 drove them to zero)
        - Cluster near 1      (active gates — classification kept them open)

    Red dashed line marks the sparsity threshold.
    Gates left of the line are counted as pruned.
    """
    gates = []
    for m in model.modules():
        if isinstance(m, PrunableLinear):
            gates.append(m.get_gates().cpu().view(-1))
    gates = torch.cat(gates).numpy()

    pruned_pct = (gates < threshold).mean() * 100

    fig, ax = plt.subplots(figsize=(8, 4))
    ax.hist(gates, bins=60, color="steelblue", edgecolor="white", linewidth=0.4)
    ax.axvline(
        x=threshold, color='crimson', linestyle='--',
        linewidth=1.8, label=f'threshold={threshold}'
    )
    ax.set_title(
        f"Gate distribution  λ={lam}   ({pruned_pct:.1f}% pruned)",
        fontsize=13
    )
    ax.set_xlabel("Gate value (0 to 1)", fontsize=12)
    ax.set_ylabel("Weight count", fontsize=12)
    ax.legend(fontsize=11)
    plt.tight_layout()

    fname = f"gate_dist_lambda_{lam}.png"
    plt.savefig(fname, dpi=150)
    plt.close(fig)
    print(f"  Saved {fname}")


# ── Main ──────────────────────────────────────────────────────
def main():
    print("Loading CIFAR-10 …")
    train_loader, test_loader = get_loaders()

    lambda_values = [0.1, 0.5, 1.0, 2.0]
    results = []

    for lam in lambda_values:
        print(f"\n{'='*56}")
        print(f"  Training  λ = {lam}")
        print(f"{'='*56}")

        model = PrunableMLP()
        train(model, train_loader, lam=lam, epochs=25)

        acc = evaluate(model, test_loader)
        sp  = compute_sparsity(model)
        lsp = layerwise_sparsity(model)

        print(f"\n  Layer-wise sparsity:")
        for i, s in enumerate(lsp):
            print(f"    Layer {i+1}: {s:.1f}%")
        print(f"  Total sparsity : {sp:.1f}%")
        print(f"  Test accuracy  : {acc:.2f}%")

        results.append((lam, acc, sp))
        plot_gates(model, lam)
        torch.save(model.state_dict(), f"model_lambda_{lam}.pth")

    # ── Final results table ───────────────────────────────────
    print(f"\n{'='*56}")
    print(f"  FINAL RESULTS")
    print(f"{'='*56}")
    print(f"  {'Lambda':<10}  {'Accuracy':>10}  {'Sparsity':>10}")
    print(f"  {'-'*36}")
    for lam, acc, sp in results:
        print(f"  {lam:<10}  {acc:>9.2f}%  {sp:>9.1f}%")


if __name__ == "__main__":
    main()